/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author anton
 */
public class FrmCompra extends javax.swing.JInternalFrame {
// Servicios para enlazar la vista con la lógica de negocio
    private servicio.ProductoService servicioProducto;
    private servicio.CompraService servicioCompra;
    
    // Objeto en memoria para retener el producto encontrado
    private modelo.Producto productoSeleccionado;
    
    // Lista dinámica que actuará como el "carrito de compras de stock" en RAM
    private java.util.List<modelo.DetalleCompra> carrito;
    
    // Modelo para gestionar dinámicamente las filas de la JTable
    private javax.swing.table.DefaultTableModel modeloTabla;
    
    // Control numérico de los totales acumulados
    private double subtotalAcumulado = 0.0;
    private final double PORCENTAJE_IMPUESTO = 0.18; // 18% impuesto base
    
    
    public FrmCompra() {
        initComponents();
        
        // Inicializamos las capas de servicio y nuestra lista provisional
        servicioProducto = new servicio.ProductoService();
        servicioCompra = new servicio.CompraService();
        carrito = new java.util.ArrayList<>();
        
        // Configuramos la estructura interna de la JTable
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] { "Código", "Descripción", "Cantidad", "Precio Compra", "Subtotal" }
        ) {
            // Impedimos que el usuario edite las celdas directamente haciendo doble clic
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCarrito.setModel(modeloTabla);
        
        // Deshabilitamos los campos informativos para evitar ediciones accidentales
        txtNombreProducto.setEditable(false);
        txtSubtotalFinal.setEditable(false);
        txtImpuestoFinal.setEditable(false);
        txtTotalFinal.setEditable(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotalFinal = new javax.swing.JTextField();
        txtImpuestoFinal = new javax.swing.JTextField();
        txtTotalFinal = new javax.swing.JTextField();
        btnRegistrarCompra = new javax.swing.JButton();

        jLabel1.setText("Código Producto");

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        jLabel2.setText("Producto:");

        txtNombreProducto.setEditable(false);

        jLabel3.setText("Cantidad");

        txtCantidad.setText("1");

        jLabel4.setText("Precio Compra");

        txtPrecioCompra.setText("0.00");

        btnAgregar.setText("Agregar al Carrito");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio Compra", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrito);

        jLabel5.setText("Subtotal");

        jLabel6.setText("Impuesto (18%)");

        jLabel7.setText("Total Compra");

        txtSubtotalFinal.setEditable(false);
        txtSubtotalFinal.setText("0.00");

        txtImpuestoFinal.setEditable(false);
        txtImpuestoFinal.setText("0.00");

        txtTotalFinal.setEditable(false);
        txtTotalFinal.setText("0.00");

        btnRegistrarCompra.setText("Registrar Compra");
        btnRegistrarCompra.addActionListener(this::btnRegistrarCompraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdProducto)
                                    .addComponent(txtNombreProducto)
                                    .addComponent(txtCantidad)
                                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarProducto)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubtotalFinal)
                            .addComponent(txtImpuestoFinal)
                            .addComponent(txtTotalFinal)
                            .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSubtotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCompra)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
String textoId = txtIdProducto.getText().trim();
        
        if (textoId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del producto.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            int idProducto = Integer.parseInt(textoId);
            
            // Buscamos el producto en el catálogo general
            productoSeleccionado = servicioProducto.buscar(idProducto);
            
            if (productoSeleccionado != null && productoSeleccionado.getActivo()) {
                // Si existe y está activo, mostramos su descripción
                txtNombreProducto.setText(productoSeleccionado.getNombre());
                txtPrecioCompra.setText("0.00");
                txtCantidad.requestFocus(); // Movemos el cursor a la cantidad
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "El producto no existe en el catálogo o no está activo.");
                limpiarBusquedaProducto();
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código del producto debe ser un número entero válido.");
            limpiarBusquedaProducto();
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
if (productoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un producto antes de agregarlo.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // Capturamos y validamos numéricamente los inputs
            double cantidad = Double.parseDouble(txtCantidad.getText().trim());
            double precioCompra = Double.parseDouble(txtPrecioCompra.getText().trim());
            
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad ingresada debe ser mayor que cero.");
                txtCantidad.requestFocus();
                return;
            }
            if (precioCompra <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El precio de compra debe ser mayor que cero.");
                txtPrecioCompra.requestFocus();
                return;
            }
            
            // Instanciamos el objeto de la entidad detalle (POO)
            modelo.DetalleCompra detalle = new modelo.DetalleCompra();
            detalle.setProducto(productoSeleccionado);
            detalle.setCantidad(cantidad);
            detalle.setPrecioCompra(precioCompra);
            
            // Acumulamos el registro en nuestra lista RAM
            carrito.add(detalle);
            
            // Pintamos la fila correspondiente de forma visual en la JTable
            Object[] fila = new Object[5];
            fila[0] = productoSeleccionado.getIdProducto();
            fila[1] = productoSeleccionado.getNombre();
            fila[2] = cantidad;
            fila[3] = precioCompra;
            fila[4] = detalle.getSubtotal(); // Calcula automáticamente cantidad * precioCompra
            
            modeloTabla.addRow(fila);
            
            // Recalculamos los importes globales del formulario
            actualizarTotales(detalle.getSubtotal());
            
            // Limpiamos los selectores para la siguiente línea
            limpiarBusquedaProducto();
            txtCantidad.setText("1");
            txtPrecioCompra.setText("0.00");
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para la cantidad y el precio.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
if (carrito.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El detalle de la compra está vacío. Añada productos antes de guardar.");
            return;
        }
        
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Desea asentar de forma definitiva esta compra de mercadería?", 
                "Confirmar Compra", javax.swing.JOptionPane.YES_NO_OPTION);
                
        if (confirmar != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            // Instanciamos el objeto cabecera de la Compra
            modelo.Compra compra = new modelo.Compra();
            
            // Marcamos la marca de tiempo actual del servidor local
            long milisegundos = System.currentTimeMillis();
            java.sql.Date fechaActual = new java.sql.Date(milisegundos);
            compra.setFecha(fechaActual);
            
            // Inyectamos los montos financieros calculados dinámicamente
            compra.setValorImpuesto(PORCENTAJE_IMPUESTO);
            
            double impuesto = subtotalAcumulado * PORCENTAJE_IMPUESTO;
            double total = subtotalAcumulado + impuesto;
            compra.setImpuesto(impuesto);
            compra.setTotal(total);
            

            
            
            /**
            // Como la tabla "compra" requiere obligatoriamente un "id_usuario",
            // usamos temporalmente el ID 1 para registrar compras sin errores de SQL.
            * */
            
            modelo.Usuario usuarioSimulado = new modelo.Usuario();
            usuarioSimulado.setIdUsuario(1); 
            compra.setUsuario(usuarioSimulado);

            /**
             *    cambiala el nombre de la variable por la tuya.
            compra.setUsuario( servicio.UsuarioService.getUsuarioLogueado() );
            **/
            
            
            
            
            // Despachamos el paquete transaccional (Maestro-Detalle) a la capa de Servicio
            if (servicioCompra.insertar(compra, carrito)) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Compra de stock registrada exitosamente!");
                limpiarFormularioCompleto();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error de persistencia: No se pudo registrar la compra.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error crítico inesperado: " + e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed

    
    
    private void limpiarBusquedaProducto() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        productoSeleccionado = null;
        txtIdProducto.requestFocus();
    }

    private void actualizarTotales(double subtotalDelProducto) {
        subtotalAcumulado += subtotalDelProducto;
        
        double impuestoCalculado = subtotalAcumulado * PORCENTAJE_IMPUESTO;
        double totalCalculado = subtotalAcumulado + impuestoCalculado;
        
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", impuestoCalculado));
        txtTotalFinal.setText(String.format("%.2f", totalCalculado));
    }

    private void limpiarFormularioCompleto() {
        limpiarBusquedaProducto();
        txtCantidad.setText("1");
        txtPrecioCompra.setText("0.00");
        
        modeloTabla.setRowCount(0); // Resetea la JTable visual
        carrito.clear();            // Limpia el ArrayList de memoria RAM
        
        subtotalAcumulado = 0.0;
        txtSubtotalFinal.setText("0.00");
        txtImpuestoFinal.setText("0.00");
        txtTotalFinal.setText("0.00");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtImpuestoFinal;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtSubtotalFinal;
    private javax.swing.JTextField txtTotalFinal;
    // End of variables declaration//GEN-END:variables
}
