/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;
import javax.swing.JOptionPane;
import modelo.Compra;
import modelo.Usuario;
import servicio.UsuarioService;

/**
 *
 * @author anton
 */
public class FrmCompra extends javax.swing.JInternalFrame {
// Servicios para enlazar la vista con la lógica de negocio
    private servicio.ProductoService servicioProducto;
    private servicio.CompraService servicioCompra;
    
    // Objeto en memoria para retener el producto encontrado
    private modelo.Producto productoSeleccionado;
    
    // Lista dinámica que actuará como el "carrito de compras de stock" en RAM
    private java.util.List<modelo.DetalleCompra> carrito;
    
    // Modelo para gestionar dinámicamente las filas de la JTable
    private javax.swing.table.DefaultTableModel modeloTabla;
    
    // Control numérico de los totales acumulados
    private double subtotalAcumulado = 0.0;
    private final double PORCENTAJE_IMPUESTO = 0.18; // 18% impuesto base
    
    private boolean modoConsulta = false;
    private int idCompraConsulta = 0;
    
    
    public FrmCompra() {
        initComponents();
        
        // Inicializamos las capas de servicio y nuestra lista provisional
        servicioProducto = new servicio.ProductoService();
        servicioCompra = new servicio.CompraService();
        carrito = new java.util.ArrayList<>();
        
        // Configuramos la estructura interna de la JTable
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] { "Código", "Descripción", "Cantidad", "Precio Compra", "Subtotal" }
        ) {
            // Impedimos que el usuario edite las celdas directamente haciendo doble clic
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCarrito.setModel(modeloTabla);
        
        // Deshabilitamos los campos informativos para evitar ediciones accidentales
        txtNombreProducto.setEditable(false);
        txtSubtotalFinal.setEditable(false);
        txtImpuestoFinal.setEditable(false);
        txtTotalFinal.setEditable(false);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnBuscarProducto = new javax.swing.JButton();
        txtIdProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnRegistrarCompra = new javax.swing.JButton();
        btnRegistrarCompra1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSubtotalFinal = new javax.swing.JTextField();
        txtImpuestoFinal = new javax.swing.JTextField();
        txtTotalFinal = new javax.swing.JTextField();

        setTitle("Registro de Compra");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("REGISTRO DE COMPRAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        txtIdProducto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtNombreProducto.setEditable(false);

        jLabel3.setText("Cantidad");

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setText("1");

        jLabel4.setText("Prc.Compra");

        txtPrecioCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompra.setText("0.00");

        btnAgregar.setText("Agregar al Carrito");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE COMPRA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio Compra", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrito);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        btnRegistrarCompra.setText("Registrar Compra");
        btnRegistrarCompra.addActionListener(this::btnRegistrarCompraActionPerformed);

        btnRegistrarCompra1.setLabel("Salir");
        btnRegistrarCompra1.addActionListener(this::btnRegistrarCompra1ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarCompra1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCompra)
                    .addComponent(btnRegistrarCompra1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMPORTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel5.setText("Subtotal");

        jLabel6.setText("Impuesto (18%)");

        jLabel7.setText("Total Compra");

        txtSubtotalFinal.setEditable(false);
        txtSubtotalFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubtotalFinal.setText("0.00");

        txtImpuestoFinal.setEditable(false);
        txtImpuestoFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtImpuestoFinal.setText("0.00");

        txtTotalFinal.setEditable(false);
        txtTotalFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalFinal.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(txtSubtotalFinal)
                    .addComponent(txtTotalFinal))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSubtotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(295, 295, 295)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
String textoId = txtIdProducto.getText().trim();
        
        if (textoId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del producto.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            int idProducto = Integer.parseInt(textoId);
            
            // Buscamos el producto en el catálogo general
            productoSeleccionado = servicioProducto.buscar(idProducto);
            
            if (productoSeleccionado != null && productoSeleccionado.getActivo()) {
                // Si existe y está activo, mostramos su descripción
                txtNombreProducto.setText(productoSeleccionado.getNombre());
                txtPrecioCompra.setText("0.00");
                txtCantidad.requestFocus(); // Movemos el cursor a la cantidad
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "El producto no existe en el catálogo o no está activo.");
                limpiarBusquedaProducto();
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código del producto debe ser un número entero válido.");
            limpiarBusquedaProducto();
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
if (productoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un producto antes de agregarlo.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // Capturamos y validamos numéricamente los inputs
            double cantidad = Double.parseDouble(txtCantidad.getText().trim());
            double precioCompra = Double.parseDouble(txtPrecioCompra.getText().trim());
            
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad ingresada debe ser mayor que cero.");
                txtCantidad.requestFocus();
                return;
            }
            if (precioCompra <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "El precio de compra debe ser mayor que cero.");
                txtPrecioCompra.requestFocus();
                return;
            }
            
            // Instanciamos el objeto de la entidad detalle (POO)
            modelo.DetalleCompra detalle = new modelo.DetalleCompra();
            detalle.setProducto(productoSeleccionado);
            detalle.setCantidad(cantidad);
            detalle.setPrecioCompra(precioCompra);
            
            // Acumulamos el registro en nuestra lista RAM
            carrito.add(detalle);
            
            // Pintamos la fila correspondiente de forma visual en la JTable
            Object[] fila = new Object[5];
            fila[0] = productoSeleccionado.getIdProducto();
            fila[1] = productoSeleccionado.getNombre();
            fila[2] = cantidad;
            fila[3] = precioCompra;
            fila[4] = detalle.getSubtotal(); // Calcula automáticamente cantidad * precioCompra
            
            modeloTabla.addRow(fila);
            
            // Recalculamos los importes globales del formulario
            actualizarTotales(detalle.getSubtotal());
            
            // Limpiamos los selectores para la siguiente línea
            limpiarBusquedaProducto();
            txtCantidad.setText("1");
            txtPrecioCompra.setText("0.00");
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos para la cantidad y el precio.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
        if (carrito.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El detalle de la compra está vacío. Añada productos antes de guardar.");
            return;
        }
        
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Desea asentar de forma definitiva esta compra de mercadería?", 
                "Confirmar Compra", javax.swing.JOptionPane.YES_NO_OPTION);
                
        if (confirmar != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            // Instanciamos el objeto cabecera de la Compra
            modelo.Compra compra = new modelo.Compra();
            
            // Marcamos la marca de tiempo actual del servidor local
            long milisegundos = System.currentTimeMillis();
            java.sql.Date fechaActual = new java.sql.Date(milisegundos);
            compra.setFecha(fechaActual);
            
            // Inyectamos los montos financieros calculados dinámicamente
            compra.setValorImpuesto(PORCENTAJE_IMPUESTO);
            
            double impuesto = subtotalAcumulado * PORCENTAJE_IMPUESTO;
            double total = subtotalAcumulado + impuesto;
            compra.setImpuesto(impuesto);
            compra.setTotal(total);
                        
            //Se captura el id del usuario logueado
            Usuario usuario = UsuarioService.getUsuarioLogueado();
            if (usuario == null) {
               JOptionPane.showMessageDialog(this, "No existe un usuario autenticado.");
               return;
            }
            compra.setUsuario(usuario);

                        // Despachamos el paquete transaccional (Maestro-Detalle) a la capa de Servicio
            if (servicioCompra.insertar(compra, carrito)) {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Compra de stock registrada exitosamente!");
                limpiarFormularioCompleto();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error de persistencia: No se pudo registrar la compra.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error crítico inesperado: " + e.getMessage());
        }        
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed

    private void btnRegistrarCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompra1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegistrarCompra1ActionPerformed
   
    private void limpiarBusquedaProducto() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        productoSeleccionado = null;
        txtIdProducto.requestFocus();
    }

    private void actualizarTotales(double subtotalDelProducto) {
        subtotalAcumulado += subtotalDelProducto;
        
        double impuestoCalculado = subtotalAcumulado * PORCENTAJE_IMPUESTO;
        double totalCalculado = subtotalAcumulado + impuestoCalculado;
        
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", impuestoCalculado));
        txtTotalFinal.setText(String.format("%.2f", totalCalculado));
    }

    private void limpiarFormularioCompleto() {
        limpiarBusquedaProducto();
        txtCantidad.setText("1");
        txtPrecioCompra.setText("0.00");
        
        modeloTabla.setRowCount(0); // Resetea la JTable visual
        carrito.clear();            // Limpia el ArrayList de memoria RAM
        
        subtotalAcumulado = 0.0;
        txtSubtotalFinal.setText("0.00");
        txtImpuestoFinal.setText("0.00");
        txtTotalFinal.setText("0.00");
    }
    
    public FrmCompra(int idCompra) {
        this(); 

        this.modoConsulta = true;
        this.idCompraConsulta = idCompra;

        cargarCompra(idCompra);
        bloquearFormulario();
    }
    
    private void cargarCompra(int idCompra){
        modelo.Compra compra = servicioCompra.buscarCompra(idCompra);
        
        if(compra == null){
            JOptionPane.showMessageDialog(this,"No existe la compra.");
            return;
        }
        
        carrito.clear();
        modeloTabla.setRowCount(0);
        subtotalAcumulado = 0;
        
        java.util.List<modelo.DetalleCompra> detalles = servicioCompra.listarDetalleCompra(idCompra);
        
        for(modelo.DetalleCompra detalle : detalles){
            carrito.add(detalle);
            
            modeloTabla.addRow(new Object[]{
                detalle.getProducto().getIdProducto(),
                detalle.getProducto().getNombre(),
                detalle.getCantidad(),
                detalle.getPrecioCompra(),
                detalle.getSubtotal()
            });
            
            subtotalAcumulado += detalle.getSubtotal();
        }
        
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", compra.getImpuesto()));
        txtTotalFinal.setText(String.format("%.2f", compra.getTotal()));
    }
    
    private void bloquearFormulario() {
        btnBuscarProducto.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnRegistrarCompra.setEnabled(false);

        txtIdProducto.setEditable(false);
        txtCantidad.setEditable(false);
        txtPrecioCompra.setEditable(false);

        tblCarrito.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JButton btnRegistrarCompra1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtImpuestoFinal;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtSubtotalFinal;
    private javax.swing.JTextField txtTotalFinal;
    // End of variables declaration//GEN-END:variables
}
