package vista;

/**
 *
 * @author anton
 */

public class FrmVenta extends javax.swing.JInternalFrame {
// servicios para comunicarnos con la base de datos
    private servicio.ProductoService servicioProducto;
    private servicio.VentaService servicioVenta;
    
    // el objeto del producto que se encuentre al buscar
    private modelo.Producto productoSeleccionado;
    
    //la lista que actuará como nuestro "carrito de compras" interno en memoria
    private java.util.List<modelo.DetalleVenta> carrito;
    
    // el modelo para controlar y añadir filas a la JTable fácilmente
    private javax.swing.table.DefaultTableModel modeloTabla;
    
    //variables para acumular los montos totales
    private double subtotalAcumulado = 0.0;
    private final double PORCENTAJE_IMPUESTO = 0.18; // 18% de impuesto
    
public FrmVenta() {
        initComponents();
        
        // Inicializamos nuestros servicios y el carrito en memoria
        servicioProducto = new servicio.ProductoService();
        servicioVenta = new servicio.VentaService();
        carrito = new java.util.ArrayList<>();
        
        // Configuramos la tabla para que use un modelo limpio
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] { "Código", "Descripción", "Cantidad", "Precio", "Subtotal" }
        ) {
            // Hacemos que ninguna celda de la tabla sea editable directamente al hacer doble clic
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCarrito.setModel(modeloTabla);
        
        // Deshabilitamos los campos de totales para que solo muestren resultados calculados
        txtSubtotalFinal.setEditable(false);
        txtImpuestoFinal.setEditable(false);
        txtTotalFinal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSubtotalFinal = new javax.swing.JTextField();
        txtImpuestoFinal = new javax.swing.JTextField();
        txtTotalFinal = new javax.swing.JTextField();
        btnRegistrarVenta = new javax.swing.JButton();

        jLabel1.setText("Código Producto:");

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        jLabel2.setText("Producto Seleccionado:");

        txtNombreProducto.setEditable(false);

        jLabel3.setText("Cantidad");

        txtCantidad.setText("1");

        btnAgregar.setText("Agregar al Carrito");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrito);

        jLabel4.setText("Subtotal:");

        jLabel5.setText("Impuesto (18%):");

        jLabel6.setText("Importe Total:");

        txtTotalFinal.addActionListener(this::txtTotalFinalActionPerformed);

        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.addActionListener(this::btnRegistrarVentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdProducto)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarProducto)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtSubtotalFinal)
                    .addComponent(txtImpuestoFinal)
                    .addComponent(txtTotalFinal))
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnRegistrarVenta)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFinalActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
String textoId = txtIdProducto.getText().trim();
        
        // 1. Validar que el campo no esté vacío
        if (textoId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del producto.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // 2. Convertir el texto a número entero
            int idProducto = Integer.parseInt(textoId);
            
            // 3. Llamar al servicio para buscar el producto en la base de datos
            productoSeleccionado = servicioProducto.buscar(idProducto);
            
            // 4. Validar si el producto existe y está activo para la venta
            if (productoSeleccionado != null && productoSeleccionado.getActivo()) {
                // Si existe, mostramos el nombre y el precio en el campo de texto
                txtNombreProducto.setText(productoSeleccionado.getNombre() + " (Precio: S/ " + productoSeleccionado.getPrecioVenta() + ")");
                txtCantidad.requestFocus(); // Pasamos el foco a la cantidad para agilizar la venta
            } else {
                // Si no existe o está desactivado
                javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado o no se encuentra activo.");
                limpiarBusquedaProducto();
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código del producto debe ser un número entero válido.");
            limpiarBusquedaProducto();
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    // Método auxiliar para limpiar los campos de selección si la búsqueda falla
    private void limpiarBusquedaProducto() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        productoSeleccionado = null;
        txtIdProducto.requestFocus();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
// 1. Validar que se haya buscado y seleccionado un producto primero
        if (productoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un producto antes de agregarlo.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // 2. Validar la cantidad ingresada
            double cantidad = Double.parseDouble(txtCantidad.getText().trim());
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.");
                txtCantidad.requestFocus();
                return;
            }
            
            // 3. Crear el objeto DetalleVenta (POO) para nuestro carrito interno
            modelo.DetalleVenta detalle = new modelo.DetalleVenta();
            detalle.setProducto(productoSeleccionado);
            detalle.setCantidad(cantidad);
            detalle.setPrecioVenta(productoSeleccionado.getPrecioVenta());
            
            // 4. Agregar el detalle a la lista en memoria (carrito)
            carrito.add(detalle);
            
            // 5. Agregar el registro de forma visual a la JTable de la pantalla
            Object[] fila = new Object[5];
            fila[0] = productoSeleccionado.getIdProducto();
            fila[1] = productoSeleccionado.getNombre();
            fila[2] = cantidad;
            fila[3] = productoSeleccionado.getPrecioVenta();
            fila[4] = detalle.getSubtotal(); // Calcula cantidad * precio automáticamente
            
            modeloTabla.addRow(fila);
            
            // 6. Actualizar los cálculos de los totales en la pantalla
            actualizarTotales(detalle.getSubtotal());
            
            // 7. Limpiar los campos de búsqueda para el siguiente producto
            limpiarBusquedaProducto();
            txtCantidad.setText("1"); // Reseteamos la cantidad por defecto
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese una cantidad numérica válida.");
            txtCantidad.requestFocus();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Método auxiliar para recalcular los totales e impuestos automáticamente
    private void actualizarTotales(double subtotalDelProducto) {
        // Sumamos el subtotal del nuevo producto al acumulado general
        subtotalAcumulado += subtotalDelProducto;
        
        // Calculamos el impuesto (18%) y el gran total total
        double impuestoCalculado = subtotalAcumulado * PORCENTAJE_IMPUESTO;
        double totalCalculado = subtotalAcumulado + impuestoCalculado;
        
        // Pintamos los resultados en los campos de texto formateados a 2 decimales
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", impuestoCalculado));
        txtTotalFinal.setText(String.format("%.2f", totalCalculado));
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        //Validar que el carrito contenga al menos un producto
        if (carrito.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito está vacío. Debe agregar productos para registrar una venta.");
            return;
        }
        
        // Confirmación de seguridad para el usuario
        int confirmar = javax.swing.JOptionPane.showConfirmDialog (this, 
                "¿Está seguro de proceder con el registro de esta venta?", 
                "Confirmar Venta", javax.swing.JOptionPane.YES_NO_OPTION);
                
        if (confirmar != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            //Instanciar la cabecera de la Venta (POO)
            modelo.Venta venta = new modelo.Venta();
            
            // Asignamos la fecha actual del sistema para la base de datos
            long milisegundos = System.currentTimeMillis();
            java.sql.Date fechaActual = new java.sql.Date(milisegundos);
            venta.setFecha(fechaActual);
            
            // Asignamos los importes que calculamos dinámicamente en la interfaz
            venta.setValorImpuesto(PORCENTAJE_IMPUESTO);
            
            double impuesto = subtotalAcumulado * PORCENTAJE_IMPUESTO;
            double total = subtotalAcumulado + impuesto;
            venta.setImpuesto(impuesto);
            venta.setTotal(total);
            
            
            
            
            
                                                                // ATENCION
            /**
            Como la tabla "venta" requiere obligatoriamente un "id_usuario",
            usamos temporalmente el ID 1 para registrar ventas sin errores de SQL.
            **/
            modelo.Usuario usuarioSimulado = new modelo.Usuario();
            usuarioSimulado.setIdUsuario(1); 
            venta.setUsuario(usuarioSimulado);
            
            /**
            Cuando el módulo de Usuarios e Inicio de Sesión esté terminado, 
            borra las 3 líneas de arriba (del usuario simulado) y reemplaza por la linea de abajo.
           
           * 
           * Cambiar por el nombre de la variable
            venta.setUsuario( servicio.UsuarioService.getUsuarioLogueado() );
            **/
            
            
            
            
            
            
            //Invocar la capa de Servicio para procesar la transacción
            if (servicioVenta.insertar(venta, carrito)) {
                // Si la transacción SQL hace COMMIT exitoso en el DAO
                javax.swing.JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito en la base de datos!");
                limpiarFormularioCompleto();
            } else {
                // Si el DAO ejecuta un ROLLBACK ante un error
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar la venta. Verifique la consola para más detalles.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }

    // Método auxiliar para resetear toda la pantalla después de una venta exitosa
    private void limpiarFormularioCompleto() {
        limpiarBusquedaProducto();
        txtCantidad.setText("1");
        
        // Limpiamos los registros visuales de la JTable
        modeloTabla.setRowCount(0);
        
        // Limpiamos la lista interna en Ram
        carrito.clear();
        
        // Reseteamos los acumuladores numericos
        subtotalAcumulado = 0.0;
        txtSubtotalFinal.setText("0.00");
        txtImpuestoFinal.setText("0.00");
        txtTotalFinal.setText("0.00");
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtImpuestoFinal;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtSubtotalFinal;
    private javax.swing.JTextField txtTotalFinal;
    // End of variables declaration//GEN-END:variables
}
