/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Usuario;
import servicio.UsuarioService;

/**
 *
 * @author anton
 */
public class FrmVenta extends javax.swing.JInternalFrame {
// servicios para comunicarnos con la base de datos
    private servicio.ProductoService servicioProducto;
    private servicio.VentaService servicioVenta;
    
    // el objeto del producto que se encuentre al buscar
    private modelo.Producto productoSeleccionado;
    
    //la lista que actuará como nuestro "carrito de compras" interno en memoria
    private java.util.List<modelo.DetalleVenta> carrito;
    
    // el modelo para controlar y añadir filas a la JTable fácilmente
    private javax.swing.table.DefaultTableModel modeloTabla;
    
    //variables para acumular los montos totales
    private double subtotalAcumulado = 0.0;
    private final double PORCENTAJE_IMPUESTO = 0.18; // 18% de impuesto
    
    private boolean modoConsulta = false;
    private int idVentaConsulta = 0;
    
public FrmVenta() {
        initComponents();
        
        // Inicializamos nuestros servicios y el carrito en memoria
        servicioProducto = new servicio.ProductoService();
        servicioVenta = new servicio.VentaService();
        carrito = new java.util.ArrayList<>();
        
        // Configuramos la tabla para que use un modelo limpio
        modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] { "Código", "Descripción", "Cantidad", "Precio", "Subtotal" }
        ) {
            // Hacemos que ninguna celda de la tabla sea editable directamente al hacer doble clic
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCarrito.setModel(modeloTabla);
        
        // Deshabilitamos los campos de totales para que solo muestren resultados calculados
        txtSubtotalFinal.setEditable(false);
        txtImpuestoFinal.setEditable(false);
        txtTotalFinal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdProducto = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtSubtotalFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtImpuestoFinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalFinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Registro de Venta");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        txtIdProducto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(this::btnBuscarProductoActionPerformed);

        txtNombreProducto.setEditable(false);

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setText("1");
        txtCantidad.setCaretPosition(0);

        jLabel3.setText("Cantidad");

        btnAgregar.setText("Agregar al Carrito");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad)
                    .addComponent(jLabel3)
                    .addComponent(btnAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLE DE VENTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Cantidad", "Precio", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarrito);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMPORTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        txtSubtotalFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Subtotal:");

        txtImpuestoFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Impuesto (18%):");

        txtTotalFinal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTotalFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalFinal.addActionListener(this::txtTotalFinalActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Importe Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(txtSubtotalFinal)
                    .addComponent(txtTotalFinal))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addComponent(txtSubtotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImpuestoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.addActionListener(this::btnRegistrarVentaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVenta)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("REGISTRO DE VENTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFinalActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
String textoId = txtIdProducto.getText().trim();
        
        // 1. Validar que el campo no esté vacío
        if (textoId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el código del producto.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // 2. Convertir el texto a número entero
            int idProducto = Integer.parseInt(textoId);
            
            // 3. Llamar al servicio para buscar el producto en la base de datos
            productoSeleccionado = servicioProducto.buscar(idProducto);
            
            // 4. Validar si el producto existe y está activo para la venta
            if (productoSeleccionado != null && productoSeleccionado.getActivo()) {
                // Si existe, mostramos el nombre y el precio en el campo de texto
                txtNombreProducto.setText(productoSeleccionado.getNombre() + " (Precio: S/ " + productoSeleccionado.getPrecioVenta() + ")");
                txtCantidad.requestFocus(); // Pasamos el foco a la cantidad para agilizar la venta
            } else {
                // Si no existe o está desactivado
                javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado o no se encuentra activo.");
                limpiarBusquedaProducto();
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código del producto debe ser un número entero válido.");
            limpiarBusquedaProducto();
        }
    }                                                 

    // Método auxiliar para limpiar los campos de selección si la búsqueda falla
    private void limpiarBusquedaProducto() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        productoSeleccionado = null;
        txtIdProducto.requestFocus();
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
// 1. Validar que se haya buscado y seleccionado un producto primero
        if (productoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un producto antes de agregarlo.");
            txtIdProducto.requestFocus();
            return;
        }
        
        try {
            // 2. Validar la cantidad ingresada
            double cantidad = Double.parseDouble(txtCantidad.getText().trim());
            if (cantidad <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor que cero.");
                txtCantidad.requestFocus();
                return;
            }
            
            // 3. Crear el objeto DetalleVenta (POO) para nuestro carrito interno
            modelo.DetalleVenta detalle = new modelo.DetalleVenta();
            detalle.setProducto(productoSeleccionado);
            detalle.setCantidad(cantidad);
            detalle.setPrecioVenta(productoSeleccionado.getPrecioVenta());
            
            // 4. Agregar el detalle a la lista en memoria (carrito)
            carrito.add(detalle);
            
            // 5. Agregar el registro de forma visual a la JTable de la pantalla
            Object[] fila = new Object[5];
            fila[0] = productoSeleccionado.getIdProducto();
            fila[1] = productoSeleccionado.getNombre();
            fila[2] = cantidad;
            fila[3] = productoSeleccionado.getPrecioVenta();
            fila[4] = detalle.getSubtotal(); // Calcula cantidad * precio automáticamente
            
            modeloTabla.addRow(fila);
            
            // 6. Actualizar los cálculos de los totales en la pantalla
            actualizarTotales(detalle.getSubtotal());
            
            // 7. Limpiar los campos de búsqueda para el siguiente producto
            limpiarBusquedaProducto();
            txtCantidad.setText("1"); // Reseteamos la cantidad por defecto
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese una cantidad numérica válida.");
            txtCantidad.requestFocus();
        }
    }                                          

    // Método auxiliar para recalcular los totales e impuestos automáticamente
    private void actualizarTotales(double subtotalDelProducto) {
        // Sumamos el subtotal del nuevo producto al acumulado general
        subtotalAcumulado += subtotalDelProducto;
        
        // Calculamos el impuesto (18%) y el gran total total
        double impuestoCalculado = subtotalAcumulado * PORCENTAJE_IMPUESTO;
        double totalCalculado = subtotalAcumulado + impuestoCalculado;
        
        // Pintamos los resultados en los campos de texto formateados a 2 decimales
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", impuestoCalculado));
        txtTotalFinal.setText(String.format("%.2f", totalCalculado));
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        //Validar que el carrito contenga al menos un producto
        if (carrito.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito está vacío. Debe agregar productos para registrar una venta.");
            return;
        }
        
        // Confirmación de seguridad para el usuario
        int confirmar = javax.swing.JOptionPane.showConfirmDialog (this, 
                "¿Está seguro de proceder con el registro de esta venta?", 
                "Confirmar Venta", javax.swing.JOptionPane.YES_NO_OPTION);
                
        if (confirmar != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        try {
            //Instanciar la cabecera de la Venta (POO)
            modelo.Venta venta = new modelo.Venta();
            
            // Asignamos la fecha actual del sistema para la base de datos
            long milisegundos = System.currentTimeMillis();
            java.sql.Date fechaActual = new java.sql.Date(milisegundos);
            venta.setFecha(fechaActual);
            
            // Asignamos los importes que calculamos dinámicamente en la interfaz
            venta.setValorImpuesto(PORCENTAJE_IMPUESTO);
            
            double impuesto = subtotalAcumulado * PORCENTAJE_IMPUESTO;
            double total = subtotalAcumulado + impuesto;
            venta.setImpuesto(impuesto);
            venta.setTotal(total);
          
            //Se captura el id del usuario logueado
            Usuario usuario = UsuarioService.getUsuarioLogueado();
            if (usuario == null) {
               JOptionPane.showMessageDialog(this, "No existe un usuario autenticado.");
               return;
            }
            venta.setUsuario(usuario);
            
                        
            //Invocar la capa de Servicio para procesar la transacción
            if (servicioVenta.insertar(venta, carrito)) {
                // Si la transacción SQL hace COMMIT exitoso en el DAO
                javax.swing.JOptionPane.showMessageDialog(this, "¡Venta registrada con éxito en la base de datos!");
                limpiarFormularioCompleto();
            } else {
                // Si el DAO ejecuta un ROLLBACK ante un error
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo registrar la venta. Verifique la consola para más detalles.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
        }
    }

    // Método auxiliar para resetear toda la pantalla después de una venta exitosa
    private void limpiarFormularioCompleto() {
        limpiarBusquedaProducto();
        txtCantidad.setText("1");
        
        // Limpiamos los registros visuales de la JTable
        modeloTabla.setRowCount(0);
        
        // Limpiamos la lista interna en Ram
        carrito.clear();
        
        // Reseteamos los acumuladores numericos
        subtotalAcumulado = 0.0;
        txtSubtotalFinal.setText("0.00");
        txtImpuestoFinal.setText("0.00");
        txtTotalFinal.setText("0.00");
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public FrmVenta(int idVenta) {
        this(); 

        this.modoConsulta = true;
        this.idVentaConsulta = idVenta;

        cargarVenta(idVenta);
        bloquearFormulario();
    }
    
    private void cargarVenta(int idVenta){
        modelo.Venta venta = servicioVenta.buscarVenta(idVenta);
        
        if(venta == null){
            JOptionPane.showMessageDialog(this,"No existe la venta.");
            return;
        }
        
        carrito.clear();
        modeloTabla.setRowCount(0);
        subtotalAcumulado = 0;
        
        java.util.List<modelo.DetalleVenta> detalles = servicioVenta.listarDetalleVenta(idVenta);
        
        for(modelo.DetalleVenta detalle : detalles){
            carrito.add(detalle);
            
            modeloTabla.addRow(new Object[]{
                detalle.getProducto().getIdProducto(),
                detalle.getProducto().getNombre(),
                detalle.getCantidad(),
                detalle.getPrecioVenta(),
                detalle.getSubtotal()
            });
            
            subtotalAcumulado += detalle.getSubtotal();
        }
        
        txtSubtotalFinal.setText(String.format("%.2f", subtotalAcumulado));
        txtImpuestoFinal.setText(String.format("%.2f", venta.getImpuesto()));
        txtTotalFinal.setText(String.format("%.2f", venta.getTotal()));
    }
    
    private void bloquearFormulario() {
        btnBuscarProducto.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnRegistrarVenta.setEnabled(false);

        txtIdProducto.setEditable(false);
        txtCantidad.setEditable(false);

        tblCarrito.setEnabled(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtImpuestoFinal;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtSubtotalFinal;
    private javax.swing.JTextField txtTotalFinal;
    // End of variables declaration//GEN-END:variables
}
